### PR TITLE
Ignore TypeScript definition files

### LINKED ISSUE #65: Type definition files should not attempt to be loaded
## 🐛 Bug Report

When using `includeTypeScript: true`, fastify-autload will attempt to load type definition files (`.d.ts`), causing syntax errors, such as _Cannot use import statement outside a module_.

This happens when Node is started into a directory built from TypeScript sources into a set of `.js` & `.d.ts` files.

## To Reproduce

Reproduction repository available here:
https://github.com/franky47/fastify-autoload-65

## Expected behavior

Since Node.js cannot understand type definition files, and they contain no runtime code, I believe the extension `.d.ts` should be ignored, even when `includeTypeScript` is true.

## Your Environment

- *node version*: 13.7.0
- *fastify version*: 2.11.0
- *fastify-autoload version*: 1.2.0
- *os*: macOS

### PR DESCRIPTION
**Pull request by franky47**
Closes #65.

#### Checklist

- [x] run `npm run test` and `npm run benchmark` _(no benchmark in this plugin)_
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ module.exports = function (fastify, opts, next) {
     ? /^index\.(ts|js)$/im
     : /^index\.js$/im
   const scriptPattern = opts.includeTypeScript
-    ? /\.(ts|js)$/im
+    ? /((?<!\.d)\.ts|\.js)$/im // For .ts files, ignore .d.ts, see #65
```
Comment (Eomm) [inline index.js]: CI is failing for

> not ok Invalid regular expression: /((?<!\.d)\.ts|\.js)$/: Invalid group

Could you change the regexp to avoid the Negative lookbehind?

Comment (franky47) [reply index.js]: Yeah I did that on my fork, but the commit did not make it here, that's weird..

**Comment by mcollina** [comment]
Would you mind to add a unit test?

**Comment by franky47** [comment]
I added a .d.ts file that crashed the tests before updating the regex, do you have another test in mind ?
